# The build context is the repository root; keep state and VCS metadata out of
# it so an unrelated `terraform apply` does not bust the build cache.
.git
.github
e2e/tikv/aws/terraform/.terraform
e2e/tikv/aws/terraform/terraform.tfstate*
e2e/tikv/aws/config.mk
e2e/tikv/gcp/terraform/.terraform
e2e/tikv/gcp/terraform/terraform.tfstate*
e2e/tikv/gcp/config.mk
*.test
